### ISSUE TITLE
Year

### ISSUE THREAD

**Issue by FR0ST1N** [Gopinath001/Gopinath001.github.io#1]
Use `getFullYear()` to set year in this line ` <span class="year"><span>2019</span></span>`

**Comment by Gopinath001** [comment]
Hot damn

**Comment by FR0ST1N** [comment]
ikr.. this changes everything 😮

**Comment by Gopinath001** [comment]
make a pull req?

**Comment by FR0ST1N** [comment]
#2 here u go

**Comment by Gopinath001** [comment]
fixed  on this #2 .
